### ISSUE TITLE
Broken on Outlook 2007 and Outlook 2010

### ISSUE THREAD

**Issue by jaredpalmer** [ueno-llc/newsletter#1]
👋 Hey! This is really nice setup for email production. I've been using using grunt-email-workflow for years and this setup is very very cool. However, I ran your default newsletter through Litmus for email client testing and it's not great in Outlook 2010 and 2007. That may or may not matter to y'all, but a ton of folks still use these email apps (especially at financial institutions). Just putting on your radar. 

FWIW I think it has to do with you usage of margin instead of padding which Outlook doesn't respect. 

![ol2010-vertical-allowed-1366](https://user-images.githubusercontent.com/4060187/46748766-4b8ac300-cc82-11e8-9a07-b31fbd2f6e8c.png)
![ol2007-vertical-allowed-1366](https://user-images.githubusercontent.com/4060187/46748772-4ded1d00-cc82-11e8-8786-d3e9a9255854.png)

**Comment by gakimball** [comment]
Hey, thanks for swinging by! Glad you like the setup. I'd like to move it to something [React-based](https://github.com/gakimball/react-inky) in the future, because at this point in my life I think I'm done working with Handlebars haha.

Earlier iterations of this template had a more bulletproof-design. We used tables for everything, and table-based spacers instead of margins. However, a year in to the newsletter's life, we've found zero usage of older mail clients. Our mailing list stats show that 1% of our subscribers open the newsletter in Outlook 2016, so we test that, but nothing older.

The newsletter's design has also grown in scope over the last year, so to keep it under Gmail's ~100kb limit, we started stripping out tables in favor of `<div>`s, and replaced the table-based spacers with CSS margins, among other things. This allowed us to fit more stuff into one email, while not sacrificing compatibility with any clients used by our subscribers.

Based on our mailing list statistics, here's what we mainly test on:

- Outlook 2016
- macOS/iOS Mail
- Android/iOS/Web Gmail (+ G Suite)
- Android/iOS/Web Inbox

Outlook Mobile did pop up in our statistics (at 1.2% of subscribers) as recently as the month or so ago, and we haven't had time to look at that specifically yet.

If, in the future, we see an uptick in subscribers using older mail clients, we'll definitely reverse course on the HTML, or at least find more of a middle ground. Our marketing folks like having a lot of stuff in each newsletter, but that has to be balanced with having bulletproof HTML, depending on our subscriber base.
